### ISSUE TITLE
Cybis - Application not present.

### ISSUE THREAD

**Issue by betzburger** [kej715/DtCyber#109]
Hi,

I try to run CYBIS on NOS 2.8.7 but the Terminal says: "APPLICATION NOT PRESENT."
Most probably I missed something to do.

README says I need to input 'CYBIS.' somewhere but I don't get it.
( IAF and CHESS 4.9 runs fine!! )

Need some help here, please.

Cheers,
Peter

**Comment by pschow** [comment]
The "CYBIS." command is issued from the dual-display console to bring up
the subsystem, not from a terminal. Hopefully this makes sense but let me
know otherwise.

**Comment by betzburger** [comment]
OK. I did enter it into the dual-display console and I saw it attached things and - well - something happened.
BUT... it is still the same issue. The graphical display does not come and it says APPLICATION NOT PRESENT. I also tried pterm on port 8005 but it is the same.

**Comment by kej715** [comment]
Hi Peter,

Entering "CYBIS." on the system console should start CYBIS. If CYBIS starts
successfully, five system jobs should appear in control points 3 - 7, as
shown in the attached screenshot. In particular, if you do not see PNI1 at
control point 6, you will not be able to log into CYBIS. PNI is the "PLATO
Network Interface" program, providing access to CYBIS from PLATO terminals
(e.g., PTerm or the PLATO web terminal emulator).

If CYBIS does not start successfully, it should issue messages to the
system dayfile providing clues about why it failed to start.

Which ready-to-run NOS 2.8.7 package are you using, or did you perform an
installation of NOS 2.8.7 from scratch? If UEM has not been initialized
properly, this can prevent CYBIS from starting successfully. If that is the
case, you can try starting DtCyber using the "manual" profile, as in:

      sudo ../dtcyber manual

then enter these commands at startup:

O

P

D=YES <enter>

NEXT. <enter>
]

INITIALIZE,AL,5. <enter>

GO. <enter>


Note that equipment 5 is the UEM device in the nos287-full-865
and nos287-full-875 ready to run packages. It is not defined in
the nos287-full-875-beast package, so if you are running that package, and
CYBIS is not starting successfully, something else has gone wrong, and the
system dayfile should provide clues.

cheers,
Kevin

[image: image.png]

**Comment by betzburger** [comment]
I guess I did something wrong anywhere and I do not have any skills to repair things on this machine. So I decided to move this millions of dollar machine into the trash and downloaded a new one from Github :-)

NOW IT WORKS! Thank you guys.
