### ISSUE TITLE
Make commands case insensitive in the operator window

### ISSUE THREAD

**Issue by Hal-Barnes** [kej715/DtCyber#11]
Very minor request, but - I often have caps lock on when using DtCyber from a terminal window.  Switching over to the operator window I have to turn caps lock off to enter a command - and of course, I never remember to do that.  Making commands in the operator window case insensitive would be nice.  I hesitate to open a request for something so minor but it would be convenient.  Thanks!

**Comment by Hal-Barnes** [comment]
...

**Comment by kej715** [comment]
Done.

**Comment by Hal-Barnes** [comment]
Hello Kevin,

Argh!  I was actually trying to close the request the other day, it was so petty; I thought I had it in “close” status but it wanted a comment hence the “….” text.

Anyways, thanks for doing that, and I really appreciate your emails / commentary - so much knowledge and insight.

Thanks.
