### ISSUE TITLE
Failed to listen for TCP connection / Can't create socket

### ISSUE THREAD

**Issue by betzburger** [kej715/DtCyber#113]
Hello, 

DtCyber runs very well on my Raspberry as well as on my Linux Mint system.
On macOS I am facing a strange problem. I am sure this is on my side, but I am stuck.
Any hint is welcome.

This is the output after I entered "sudo node start" in NOS 2.8.7:

(init   ) file 'cyber.ini' section [cyber] line  6: model        Valid
(init   ) file 'cyber.ini' section [cyber] line  7: deadstart    Valid
(init   ) file 'cyber.ini' section [cyber] line  8: equipment    Valid
(init   ) file 'cyber.ini' section [cyber] line  9: npuConnections Valid
(init   ) file 'cyber.ini' section [cyber] line 10: operator     Valid
(init   ) file 'cyber.ini' section [cyber] line 11: helpers      Valid
(init   ) file 'cyber.ini' section [cyber] line 12: clock        Valid
(init   ) file 'cyber.ini' section [cyber] line 13: cpus         Valid
(init   ) file 'cyber.ini' section [cyber] line 14: memory       Valid
(init   ) file 'cyber.ini' section [cyber] line 15: esmbanks     Valid
(init   ) file 'cyber.ini' section [cyber] line 16: pps          Valid
(init   ) file 'cyber.ini' section [cyber] line 17: osType       Valid
(init   ) file 'cyber.ini' section [cyber] line 18: idle         Valid
(init   ) file 'cyber.ini' section [cyber] line 19: persistDir   Valid
(init   ) file 'cyber.ovl' section [npu.nos287] line  1: hostID       Valid
(init   ) file 'cyber.ovl' section [npu.nos287] line  2: couplerNode  Valid
(init   ) file 'cyber.ovl' section [npu.nos287] line  3: npuNode      Valid
(init   ) file 'cyber.ovl' section [npu.nos287] line  4: terminals    Valid
(init   ) file 'cyber.ini' section [npu.nos287] line  8: couplerNode  Valid
(init   ) file 'cyber.ini' section [npu.nos287] line  9: npuNode      Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 10: cdcnetNode   Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 16: cdcnetPrivilegedTcpPortOffset Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 17: cdcnetPrivilegedUdpPortOffset Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 22: hostID       Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 31: terminals    Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 35: terminals    Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 40: terminals    Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 46: terminals    Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 51: terminals    Valid
(init   ) file 'cyber.ini' section [npu.nos287] line 52: terminals    Valid
(init   ) Network host ID is 'NCCM01'
(init   ) Host coupler node value is 1
(init   ) NPU node value is 2
(init   ) CDCNet node value is 255
(init   ) TCP privileged port offset is 0
(init   ) UDP privileged port offset is 0
(init   ) [npu.nos287] line  4:    nje TCP port   175 CLA port 0x30 port count   1, block size 8192, destination host NCCMAX/98.0.36.170:175, source address 127.0.0.1, ping interval 600
(init   ) [npu.nos287] line 31:  trunk TCP port  2550 CLA port 0x01 port count   1, coupler node 3, destination host NCCM02/127.0.0.1:2551
(init   ) [npu.nos287] line 35:    raw TCP port  2552 CLA port 0x03 port count   1
(init   ) [npu.nos287] line 40: telnet TCP port    23 CLA port 0x04 port count  16
(init   ) [npu.nos287] line 46:  pterm TCP port  8005 CLA port 0x14 port count  16
(init   ) [npu.nos287] line 51:   hasp TCP port  2553 CLA port 0x24 port count   1, block size  400
(init   ) [npu.nos287] line 52:   hasp TCP port  2554 CLA port 0x25 port count   1, block size  400
(init   ) file 'cyber.ini' section [equipment.nos287] line 12: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 13: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 14: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 15: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 17: DD844      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 20: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 21: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 22: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 23: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 24: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 25: DD885      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 28: MDI        Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 31: CO6612     Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 34: CR3447     Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 35: LP512      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 36: CP3446     Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 39: MT679      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 40: MT679      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 41: MT679      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 42: MT679      Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 45: TPM        Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 48: MT5744     Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 49: MT5744     Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 50: MT5744     Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 51: MT5744     Valid
(init   ) file 'cyber.ini' section [equipment.nos287] line 54: DDP        Valid
(console) Failed to listen for TCP connections on port 16612
(npu_net) Can't create socket for port 175
09:31:10 DtCyber started - deadstarting NOS 2.8.7
09:31:13 DtCyber exited with status 1

**Comment by KC5VDJ** [comment]
Turn off vmnet?

**Comment by kej715** [comment]
Hi Peter,

There are a couple of possibilities:

   1. DtCyber ran previously and exited abnormally without being able to
   stop its "helper" processes properly. Enter the "ps ax" command and look
   for processes named "webterm-server", "STK4400", "rjews", and
   "console-server". Terminate these using "sudo kill <pid>", if any are
   running. If any of them are running, they might be holding ports 175 and
   16612 open.
   2. Some other process on your system is using port 175. To work around
   this, update your cyber.ovl file to choose a different port on which
   DtCyber should listen for NJE connections. Find this line in cyber.ovl:

terminals=*175*,0x30,1,nje,98.0.36.170:175,NCCMAX,B8192

and change the first occurrence of 175 to another port number, for example,
1175, as in:

terminals=*1175*,0x30,1,nje,98.0.36.170:175,NCCMAX,B8192

cheers,
Kevin

**Comment by drboone** [comment]
> (console) Failed to listen for TCP connections on port 16612
 > (NPU_net) Can't create socket for port 175

IIRC MacOS requires root permissions to bind to low ports (<1024)
or to create a SOCK_RAW socket.  Kevin, is that handled here?

De

**Comment by kej715** [comment]
Peter indicated that he tried starting DtCyber using the command “sudo node start”, so it would have been started as root and binding to port 175 would be allowed, unless another process was already bound to that port.On Dec 25, 2023, at 4:38 PM, Dennis Boone ***@***.***> wrote:﻿
 > (console) Failed to listen for TCP connections on port 16612
 > (NPU_net) Can't create socket for port 175

IIRC MacOS requires root permissions to bind to low ports (<1024)
or to create a SOCK_RAW socket.  Kevin, is that handled here?

De

**Comment by betzburger** [comment]
Port was indeed blocked by another process. I "killed" it. Maybe it had to do with things that I had to install to get everything up and running (XQuartz, Homebrew, ..) But even after I did a restart, the port is not blocked anymore and DtCyber runs fine.
Well, seems okay. now. Thanks!
