### ISSUE TITLE
Cybis install issue.

### ISSUE THREAD

**Issue by KC5VDJ** [kej715/DtCyber#116]
### Discussed in https://github.com/kej715/DtCyber/discussions/115

<div type='discussions-op-text'>

<sup>Originally posted by **KC5VDJ** January  4, 2024</sup>
The green highlighted files appeared in my personal account after adding cybis and just cybis.  Apparently this happens in the following build orders: basic -> ses, cybis, everything else; and, basic -> everything else, cybis.

This is based on Jan 2 after the textmode console commit.

The first build order, I may have been logged in during install, the second, definitely not (wasn't sure about the first time, so I didn't, not that I can see how it would make any diff).

Accounts and my PFs (cyan, except opllist and syslist, which are itemize listings of opl871 and system after all was said and done) added after basic was installed, before any optional installs.

If it matters: node install-product -s -f cybis
Without it previously having been installed; after install basic, and adding local accts by x.modval on the console, local pfs into the local accts (doubt this part matters), followed by optionals beginning with ses first, followed by the cybis install, apparently without regard to optionals installed between ses and cybis.

![Screenshot 2024-01-04 085439_085832](https://github.com/kej715/DtCyber/assets/136194499/6fbec2ed-620a-4cc1-b552-b86fe7ddec43)
</div>

**Comment by KC5VDJ** [comment]
As mentioned in the thread, the cybis install script uses fixed user index numbers beginning at 30B or 31B, yet creating users using defaults (k.c,username) after install basic, with UI=0 during creation, defaults to user index 30B.

Fixes: adjust UI numbers for cybis into something that won't conflict on an installed/running system with local user accounts, not defaults, if cybis is installed as an afterthought.

Alternately, the initial default UI for modval could be changed to not conflict with an after-the-fact install of cybis.

**Comment by kej715** [comment]
Historically, special/privileged user accounts tended to be assigned low UI
values, so it's not surprising that CYBIS wants 30B and 31B. I'll create a
modset for MODVAL that starts auto-assigned user UI's at a higher value,
e.g., 100B.

**Comment by KC5VDJ** [comment]
Sounds like a fix!  Thanks.

**Comment by kej715** [comment]
New modset NCCAUI has been added to the collection of NOS modifications.  NCCAUI ensures that automatically selected UI's begin at 171B.

To apply this modset to a previously installed NOS 2.8.7:

`sudo node modopl`
`sudo node install-product -f nos`
`sudo node make-ds-tape`

Then shutdown NOS 2.8.7, rename tapes/newds.tap to tapes/ds.tap, and re-deadstart NOS 2.8.7
