### ISSUE TITLE
PSU and RTIME rollover

### ISSUE THREAD

**Issue by KC5VDJ** [kej715/DtCyber#137]
### Discussed in https://github.com/kej715/DtCyber/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **KC5VDJ** March 17, 2024</sup>
Print file gets terminated.
Route,lfn,DC=lp. Does strange things after.  Endless spacing without line feeds?
Nos 287

Emacs hexl-mode shows 0x1CE824 ASCII NUL characters followed by the requested listings as if normal, mtr and cpumtr.  I made a copy of this if needed.  I think this can be duplicated by letting RTIME rollover, and then routing something to the printer.</div>

**Comment by wschaub** [comment]
Does it do the same thing when you route,lfn,DC=PR?

**Comment by wschaub** [comment]
Would be good to see the dayfile for what sequence of commands you used to get the file you submitted to the printer.

One possible thing I can think of off the top of my head is if you got the files out of modify but did not assemble them. printer output expects there to be format effectors in column 1 and if you print a file with column 1 not shifted over you will likely see all kinds of crazy output.  any normal utility which generates listable output will only put format effectors in column 1 and shift the actual content over 1 column.  

When I print out raw files that aren't formatted for printing I do something like COPYSBF(lfn,foo) and then ROUTE,foo,dc=pr.  this shifts everything over one column and makes a printable file without any format effectors in it.

**Comment by KC5VDJ** [comment]
I only tried DC=lp.

I did save the line printer file.  It's timestamp, along with the listing date/time, which is in the headr

**Comment by wschaub** [comment]
I just noticed you mentioned PSU.  you're not using the main site printer when you're seeing this? I don't use PSU normally.  but I would love to be able to reproduce this.

**Comment by kej715** [comment]
DC=LP and DC=PR are synonyms. It’s difficult to believe that PSU would be sensitive to RTIME. However, it definitely -is- sensitive to errant format effectors in column 1, e.g., when an unshifted file is queued to it, or when an ASCII file is sent without specifying EC=A9. It also attempts to translate format effectors to programmable VFU codes.On Mar 23, 2024, at 10:11 AM, William Schaub ***@***.***> wrote:﻿
I just noticed you mentioned PSU.  you're not using the main site printer when you're seeing this? I don't use PSU normally.  but I would love to be able to reproduce this.

**Comment by KC5VDJ** [comment]
Yeah, I just did a route to the default printer.  The only thing I could figure it was is the rollover of the time.

**Comment by KC5VDJ** [comment]
I am closing this.  It was not the RTIME rollover.

**Comment by KC5VDJ** [comment]
Operator error.
