### ISSUE TITLE
CYBIS doesn't start if password of user PLATOMF is changed

### ISSUE THREAD

**Issue by ghost** [kej715/DtCyber#144]
I wasn't sure if to report this as a bug, but since changing user passwords is a supported feature, I guess it qualifies.

**Describe the bug**
If the password of the user PLATOMF is changed, CYBIS cannot start and gives a _SECURITY CONFLICT_ error in the dayfile.

**To Reproduce**
1. Add an entry under the _[PASSWORDS]_ section, in the _site.cfg_ file to change the password of user PLATOMF. For example, _PLATOMF=PLUTOMF_
2. Run _reconfigure_ from the _[DtCyber Console] Operator>_
3. After the system is back online, go to the DSD console and type _CYBIS._
4. Configure the DSD console for _AB._
5. In the B display will appear the message _WAIT. MAKE SURE A TAPE DRIVE I_
6. Type _DAYFILE,jsn._, where _jsn_ is the JSN in the B display that shows the message mentioned in step 5.
7. Among other information, you'll see two messages that indicate a problem: _INCORRECT USER COMMAND_ and _SECURITY CONFLICT_

**Expected behavior**
Either, changing the password of the mentioned user doesn't break the start of CYBIS, or it is clearly indicated in the documentation (_README.md_) that this user's password must not be changed.

**Screenshots**
![dsdAB](https://github.com/kej715/DtCyber/assets/26465378/5b38bc01-85cd-43f2-9fab-613b309082cc)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Version 6.1.0-18-amd64

**Comment by wschaub** [comment]
Changing the password of PLATOMF doesn't gain you a lot since its a high index that isn't accepted except for system origin (console originated) jobs.  

That being said if you change PLATOMF  password I believe you need to edit the procedure SETPUN on the deadstart tape as well, it gets called by the other plato launch procedures to set the correct user index, etc.

**Comment by kej715** [comment]
Correct. The UI of PLATOMF is 377773B, so it is not possible to log into
this account interactively or via an ordinary batch job. Also correct that
the procedure SETPUN needs to be updated when the password is changed. The
updated procedure needs to be SYSEDIT'ed into the system and updated on the
deadstart tape. Nevertheless, I will be committing an update to the
automated installation procedures to do this automatically. Meanwhile, the
workaround is:

log into INSTALL user
COMMON,SYSTEM.
GTR,SYSTEM,SETPUN.PROC/SETPUN
edit SETPUN to change the default password value
ATTACH,PRODUCT/M=W.
LIBEDIT,P=PRODUCT,B=SETPUN,I=0,C.
RETURN,PRODUCT.
make new deadstart tape and re-deadstart the system

**Comment by dasta400** [comment]
Thanks a lot bot Kevin and William.

As Kevin already knows, I changed all passwords after I joined the NJE network. I was afraid somebody could be sending jobs to my system via another node.

I already discovered that changing NETOPS and SYSTEMX user passwords was a bad idea.

As I'm a newbie of CDC and NOS, could you please tell me how to see the UI of users? This way I could find myself which users are not needed for a password change.

Thanks a lot in advance.

**Comment by kej715** [comment]
H Dave,

MODVAL will show the UI of a user.

X.MODVAL.

K,jsn.

K.I/usernam

K.END


Also, if you run DIS (e.g.,. X.DIS.) and issue a USER command specifying a
username and password, DIS will show the UI of the logged-in username.

cheers,
Kevin

**Comment by dasta400** [comment]
Awesome. Thanks a lot Kevin.

**Comment by wschaub** [comment]
> Thanks a lot both Kevin and William.
> 
> As Kevin already knows, I changed all passwords after I joined the NJE network. I was afraid somebody could be sending jobs to my system via another node.
> 
> I already discovered that changing NETOPS and SYSTEMX user passwords was a bad idea.
> 
> As I'm a newbie of CDC and NOS, could you please tell me how to see the UI of users? This way I could find myself which users are not needed for a password change.
> 
> Thanks a lot in advance.

X.MODVAL(OP=L) I use frequently for this as it gives a report of all users in the system and their associated user index.

**Comment by dasta400** [comment]
> X.MODVAL(OP=L) I use frequently for this as it gives a report of all users in the system and their associated user index.

Ah, very useful one. I'll add it to my notes. Thanks a lot for sharing.
