### ISSUE TITLE
XRebindKeysym hangs

### ISSUE THREAD

**Issue by dancrossnyc** [kej715/DtCyber#36]
**Describe the bug**
On Arch Linux, `XRebindKeysym` as called from `windowThread` in `window_x11.c` seems to hang.

**To Reproduce**
1. Install arch Linux on a computer
2. Build DtCyber normally
3. Start it
4. Observe that the console window is not displayed

**Expected behavior**
At startup, the Cyber console window should be displayed.

**Desktop (please complete the following information):**
 - OS: Arch Linux (current as of 2022-12-06) on x86_64
 - DtCyber from git main (3cc73a53d10d2b15dc05a8604b54b6f3bc53f464)

**Additional context**
This stopped working after a point-release upgrade of Arch; printf debugging led to discovering the hang in `XRebindKeysym`. Comment out the sequence of rebind calls allows the program to continue normally; I haven't spent more time tracking down why `XRebindKeysym` appears to hang, but I suspect it has to do with locking the display (everything else in that function is pretty mundane: just adding an entry to a list). I cannot reproduce on e.g. macOS with XQuartz or on FreeBSD.

Incidentally, `modList` in `windowThread` is defined to have two elements, but only ever uses 1: I don't think that is relevant to this issue, just something I observed.

**Comment by dancrossnyc** [comment]
FYI, I filled https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/171 to track the underlying X issue.

**Comment by bug400** [comment]
I can confirm this issue (and the work around) on mac OS 11.6.7 running the latest XQuartz 2.8.3

**Comment by kej715** [comment]
Hi Dan,Thanks for investigating, reporting, and continuing to follow up on this issue. I will modify window_x11.c such that it does not use XRebindKeysim. Watch for a new push to the repo soon.Thanks again,KevinOn Dec 15, 2022, at 7:50 AM, bug400 ***@***.***> wrote:﻿
I can confirm this issue (and the work around) on mac OS 11.6.7 running the latest XQuartz 2.8.3

**Comment by dancrossnyc** [comment]
Thank you! I just pulled this and built it and can confirm that it addresses the issue.
