### ISSUE TITLE
Append ".txt", or something similar, to line printer output that is created when paper is unloaded.

### ISSUE THREAD

**Issue by Hal-Barnes** [kej715/DtCyber#8]
This feature request is not related to any known bug.

Using the Windows version of DtCyber, it would be convenient if the line printer output generated when paper is removed from a printer have a suffix appended, perhaps ".txt", so that double-clicking the file would open it in the appropriate application in Windows.

By default Windows does not provide a mechanism to associate an application to files w/no extension.  I think there are registry hacks that could achieve this but I avoid such hacks when possible.

**Comment by kej715** [comment]
Done

**Comment by kej715** [comment]
Done, ".txt" is now added to pathnames produced by the "remove_paper" command
