### ISSUE TITLE
Using virtual card reader

### ISSUE THREAD

**Issue by arblake** [kej715/DtCyber#99]
Lees of a bug but rather understanding operation.  I have installed DtCyber and have the NOS1.3 working. I understand that on the terminal I can hand key in commands but this is rather tedious for many tasks. How do I load a virtual card deck which I create with a simple text editor?  That also leads to using file on the computer as tapes within DtCyber.

**Comment by kej715** [comment]
Hi Adrian,

There are at least a couple of ways to submit virtual card decks to the NOS
1.3 system for execution. Local batch jobs can be submitted through the
central batch card reader, and remote batch jobs can be submitted through
the EI200 subsystem. A local batch job can be submitted to the central
batch card reader using DtCyber's "load_cards" (alias "lc") command. From
DtCyber's "Operator>" prompt, enter a command like:

lc 11,4,<pathname>


where <pathname> is the pathname of a file containing a virtual card deck
on your host computer. You can find documentation of the "load_cards"
command here on the CDC Community site
<https://codex.retro1.org/cdc:dtcyber:v5.8.sz:console.commands>. For
example, a virtual card deck that uploads and saves a text file might look
like:

JOB.
USER,GUEST,GUEST.
COPY,INPUT,MYFILE.
SAVE,MYFILE.
~eor
FIRST LINE OF FILE
SECOND LINE OF FILE
  :
  :
LAST LINE OF FILE

The special line "~eor" represents an end-of-record card. End-of-file is
similarly represented by "~eof".

A command line interface as well as a browser-based interface are available
for submitting jobs via remote job entry. Fpr example, when NOS 1.3 is
running, the browser-based interface can be accessed using the following
URL:

http://localhost:8085/rje.html?m=ei200-nos1


This browser-based user interface enables you to choose a virtual card deck
to be uploaded to the system via the EI200 subsystem. It will be submitted
as a remote batch job, and the job's output will be returned automatically
to a virtual remote batch printer window on the browser and also downloaded
to a text file. See the NOS 1.3 README.md
<https://github.com/kej715/DtCyber/tree/main/NOS1.3#installing-nos-13> file
for additional information about remote job entry
<https://github.com/kej715/DtCyber/tree/main/NOS1.3#remote-job-entry>.

cheers,
Kevin
